# Generated by Django 5.1.1 on 2024-11-08 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='LaTavolaAplikazioa/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Langilea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('postua', models.CharField(max_length=100)),
                ('kontu_zenbakia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='T2Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('vegan', models.BooleanField()),
                ('celiac', models.BooleanField()),
                ('calories', models.IntegerField()),
                ('valoration_avg', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Iritzia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testua', models.TextField()),
                ('izarrak', models.IntegerField()),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produktua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100, unique=True)),
                ('deskripzioa', models.CharField(max_length=300, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='LaTavolaAplikazioa/static/img')),
                ('prezioa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('mota', models.CharField(choices=[('hasierakoa', 'Hasierakoa'), ('lehena', 'Lehena'), ('bigarrena', 'Bigarrena'), ('gehigarria', 'Gehigarria'), ('postrea', 'Postrea'), ('kafea', 'Kafea')], max_length=100, null=True)),
                ('adin_nagusikoa', models.BooleanField(default=False)),
                ('alergenoak', models.ManyToManyField(to='LaTavolaAplikazioa.alergeno')),
            ],
        ),
        migrations.CreateModel(
            name='Eskaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banatzailea', models.CharField(max_length=100)),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('langilea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTavolaAplikazioa.langilea')),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTavolaAplikazioa.produktua')),
            ],
        ),
    ]
