# Generated by Django 5.1.2 on 2024-10-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Erabiltzailea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('jaiotze_data', models.DateField()),
                ('helbidea', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hornitzailea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Langilea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('postua', models.CharField(max_length=100)),
                ('kontu_zenbakia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Iritzia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testua', models.TextField()),
                ('izarrak', models.IntegerField()),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTavolaAplikazioa.erabiltzailea')),
            ],
        ),
        migrations.CreateModel(
            name='Produktua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('prezioa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hornitzaile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTavolaAplikazioa.hornitzailea')),
            ],
        ),
        migrations.CreateModel(
            name='Eskaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banatzailea', models.CharField(max_length=100)),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTavolaAplikazioa.erabiltzailea')),
                ('langilea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTavolaAplikazioa.langilea')),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTavolaAplikazioa.produktua')),
            ],
        ),
        migrations.CreateModel(
            name='AlergenoProduktua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alergeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTavolaAplikazioa.alergeno')),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaTavolaAplikazioa.produktua')),
            ],
        ),
    ]
