# Generated by Django 5.1.1 on 2024-10-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erabiltzailea',
            name='pasahitza',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
