# Generated by Django 5.1.1 on 2024-11-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0002_iritzia_data_alter_iritzia_izarrak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t2product',
            old_name='calories',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='t2product',
            old_name='product_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='t2product',
            name='celiac',
        ),
        migrations.RemoveField(
            model_name='t2product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='t2product',
            name='valoration_avg',
        ),
        migrations.RemoveField(
            model_name='t2product',
            name='vegan',
        ),
        migrations.AddField(
            model_name='t2product',
            name='foto',
            field=models.CharField(default='18.png', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t2product',
            name='ingredients',
            field=models.CharField(default='Patata', max_length=75),
            preserve_default=False,
        ),
    ]
