# Generated by Django 5.1.2 on 2024-10-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0004_remove_erabiltzailea_pasahitza_erabiltzailea_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erabiltzailea',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
