# Generated by Django 5.1.1 on 2024-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0005_alter_erabiltzailea_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='erabiltzailea',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
