# Generated by Django 5.1.1 on 2024-10-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0006_erabiltzailea_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erabiltzailea',
            name='jaiotze_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
