# Generated by Django 5.1.1 on 2024-10-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0007_alter_erabiltzailea_jaiotze_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erabiltzailea',
            old_name='email',
            new_name='username',
        ),
    ]
