# Generated by Django 5.1.1 on 2024-10-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0011_remove_erabiltzailea_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erabiltzailea',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='erabiltzailea',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='erabiltzailea',
            name='token',
        ),
    ]
