# Generated by Django 5.1.1 on 2024-10-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0012_remove_erabiltzailea_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
