# Generated by Django 5.1.1 on 2024-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0014_alter_eskaria_erabiltzailea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produktua',
            name='hornitzaile',
        ),
        migrations.AddField(
            model_name='produktua',
            name='alergenoak',
            field=models.ManyToManyField(to='LaTavolaAplikazioa.alergeno'),
        ),
        migrations.AddField(
            model_name='produktua',
            name='deskripzioa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='produktua',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AlergenoProduktua',
        ),
        migrations.DeleteModel(
            name='Hornitzailea',
        ),
    ]
