# Generated by Django 5.1.1 on 2024-11-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0015_remove_produktua_hornitzaile_produktua_alergenoak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produktua',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
