# Generated by Django 5.1.1 on 2024-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0015_remove_produktua_hornitzaile_produktua_alergenoak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergeno',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
