# Generated by Django 5.1.1 on 2024-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0016_alergeno_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='produktua',
            name='adin_nagusikoa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produktua',
            name='mota',
            field=models.CharField(choices=[('hasierakoa', 'Hasierakoa'), ('lehena', 'Lehena'), ('bigarrena', 'Bigarrena'), ('gehigarria', 'Gehigarria'), ('postrea', 'Postrea'), ('kafea', 'Kafea')], max_length=100, null=True),
        ),
    ]
