# Generated by Django 5.1.1 on 2024-11-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0017_alter_produktua_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produktua',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='produktuak'),
        ),
    ]
