# Generated by Django 5.1.1 on 2024-11-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0017_produktua_adin_nagusikoa_produktua_mota'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('vegan', models.BooleanField()),
                ('celiac', models.BooleanField()),
                ('calories', models.IntegerField()),
                ('valoration_avg', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
