# Generated by Django 5.1.1 on 2024-11-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0019_produktua_adin_nagusikoa_produktua_mota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergeno',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
