# Generated by Django 5.1.1 on 2024-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTavolaAplikazioa', '0020_alergeno_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produktua',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='LaTavolaAplikazioa/static/img'),
        ),
    ]
