INSERT INTO latavolaprueba.latavolaaplikazioa_produktua (izena, deskripzioa, img, prezioa, stock, mota, adin_nagusikoa) VALUES
('Bruschetta al Pomodoro', 'Tomate freskoz egindako ogi tostatua, albahaka hosto aromatikoekin eta oliba olio birjina esklusibo batekin.', '/static/img/bruschetta.png', 8.50, 15, 'Hasierakoa', FALSE),
('Carpaccio di Manzo', 'Behi haragi finak, trufa olio sotilarekin, errukula gaztarekin eta parmesano bikainekin biribilduak.', '/static/img/carpaccio.png', 12.00, 10, 'Hasierakoa', FALSE),
('Arancini di Riso', 'Errizoma krematsuz betetako bola kurruskariak, tomate murrizketa aberats batekin zerbitzatuta.', '/static/img/arancini.png', 10.50, 20, 'Hasierakoa', FALSE),
('Insalata Caprese', 'Mozzarella freskoa eta tomate heirloom koloretsuak, albahaka freskoarekin eta balsamiko murrizketa leunekin.', '/static/img/caprese.png', 9.00, 15, 'Hasierakoa', FALSE),
('Crostini di Fegato', 'Oilasko gibelez egindako kremaz betetako crostiniak, tipula karamelizatuarekin eta pistatxo birrinduekin apainduak.', '/static/img/crostini.png', 11.00, 10, 'Hasierakoa', FALSE),
('Tagliatelle al Tartufo', 'Etxeko tagliatelle finak, trufa beltz apartarekin eta parmesano esentzialaren kremaz.', '/static/img/tagliatelle.png', 16.00, 12, 'Lehena', FALSE),
('Ravioli di Ricotta e Spinaci', 'Ricotta eta espinaka goxoarekin betetako ravioli freskoak, gurin urtuzko eta salbia xerra fin batzuekin.', '/static/img/ravioli.png', 14.50, 12, 'Lehena', FALSE),
('Pappardelle al Cinghiale', 'Pappardelle italiarrak, jabali haragi usaintsuz eta belar aromatikoen dotoretasunez zerbitzatuak.', '/static/img/pappardelle.png', 17.00, 8, 'Lehena', FALSE),
('Spaghetti alle Vongole', 'Espagueti finak, txangurro freskoekin, baratxuri eta perrexil ukitu arinekin.', '/static/img/spaghetti_vongole.png', 15.00, 10, 'Lehena', FALSE),
('Lasagna Tradizionale', 'Lasagna tradizionala, haragi ukitu sofistikatuarekin eta besamel krematsuz.', '/static/img/lasagna.png', 13.50, 10, 'Lehena', FALSE),
('Osso Buco alla Milanese', 'Behiki txuleta delikatua, gremolata freskagarri eta risotto bikainarekin.', '/static/img/osso_buco.png', 22.00, 8, 'Bigarrena', FALSE),
('Saltimbocca alla Romana', 'Serrano urdaiazpikoarekin bildutako oilasko bularra, salbia aromatikoa eta ardo zuri apainarekin.', '/static/img/saltimbocca.png', 18.00, 10, 'Bigarrena', TRUE),
('Branzino al Sale', 'Gatza labean prestatutako lubina, barazki erreak eta olio esentziala lagun.', '/static/img/branzino.png', 25.00, 5, 'Bigarrena', FALSE),
('Filetto di Manzo al Barolo', 'Behi filetea Barolo ardoan prestatua, trufa pure krematsu eta biribilduarekin.', '/static/img/filetto.png', 28.00, 6, 'Bigarrena', TRUE),
('Pollo al Limone', 'Limoi usaintsuz eta belar gozoekin marinatutako oilasko bular fin-fina.', '/static/img/pollo.png', 17.00, 10, 'Bigarrena', FALSE),
('Patate al Rosmarino', 'Erramu eta baratxuriz bustitako patata kurruskariak, zapore osoa bermatuz.', '/static/img/patate_rosmarino.png', 5.50, 20, 'Gehigarria', FALSE),
('Verdure Grigliate', 'Denboraldiko barazkiak, parrillan erreak eta oliba olio birjina bikainez apainduak.', '/static/img/verdure.png', 6.00, 15, 'Gehigarria', FALSE),
('Risotto ai Funghi', 'Perretxiko krematsuz egindako risotto leun eta aberatsa.', '/static/img/risotto.png', 14.00, 10, 'Gehigarria', FALSE),
('Fagiolini al Vapore', 'Gatz ukituz eta zaporetsu zerbitzatutako babak.', '/static/img/fagiolini.png', 6.50, 20, 'Gehigarria', FALSE),
('Polenta alla Griglia', 'Polenta labean prestatua, tomate saltsa gozo batekin zerbitzatua.', '/static/img/polenta.png', 8.00, 15, 'Gehigarria', FALSE),
('Tiramisu Classico', 'Kafe eta mascarpone kremaren perfekzioa, kakao ukituarekin biribiltzeko.', '/static/img/tiramisu.png', 7.50, 12, 'Postrea', FALSE),
('Panna Cotta al Caramello', 'Karamelo murrizketarekin zerbitzatutako panna cotta krematsua.', '/static/img/panna_cotta.png', 8.00, 10, 'Postrea', FALSE),
('Profiteroles al Cioccolato', 'Esne kremaz betetako profiterolak, txokolate bero eta leunez bustiak.', '/static/img/profiteroles.png', 9.50, 12, 'Postrea', FALSE),
('Crostata di Frutta', 'Fruitu freskoz egindako tarta, urtaroaren osagai goxoekin.', '/static/img/crostata.png', 6.50, 10, 'Postrea', FALSE),
('Gelato Artigianale', 'Gelato artisau berezia, vanilla, txokolate eta pistatxozko zapore dotoreetan.', '/static/img/gelato.png', 4.50, 20, 'Postrea', FALSE),
('Caffè Espresso', 'Italiar espresso autentikoa, zapore sakon eta biziarekin.', '/static/img/espresso.png', 2.50, 30, 'Kafea', FALSE),
('Caffè Corretto', 'Espresso italiarra likore fin batekin osatua.', '/static/img/caffe_corretto.png', 3.00, 20, 'Kafea', TRUE),
('Amaro', 'Digestibo italiar sofistikatuak, freskagarri zerbitzatuak.', '/static/img/amaro.png', 4.00, 25, 'Kafea', TRUE),
('Grappa', 'Grappa tradizionala, italiar esentzia sakonarekin.', '/static/img/grappa.png', 5.00, 25, 'Kafea', TRUE),
('Limoncello', 'Limoizko likore freskoa, amaiera perfektua.', '/static/img/limoncello.png', 4.50, 20, 'Kafea', TRUE);
