INSERT INTO latavolaprueba.latavolaaplikazioa_produktua (izena, deskripzioa, img, prezioa, stock) VALUES
('Bruschetta al Pomodoro', 'Ogitartekoak tomate freskorekin, albahakarekin eta oliba olio birjina extra-rekin.', '/static/img/bruschetta.png', 8.50, 15),
('Carpaccio di Manzo', 'Behi-lontxako fina, trufa olioarekin, errukula eta parmesano zatiak gainetik.', '/static/img/carpaccio.png', 12.00, 10),
('Arancini di Riso', 'Errizoma betetako bola frijituak, tomate saltsarekin zerbitzatzen direnak.', '/static/img/arancini.png', 10.50, 20),
('Insalata Caprese', 'Mozzarella freskoa, tomate heirloom, albahaka eta balsamiko murrizketa bat.', '/static/img/caprese.png', 9.00, 15),
('Crostini di Fegato', 'Oilasko gibela, tipula karamelizatua eta pistatxoez betetako ogitartekoak.', '/static/img/crostini.png', 11.00, 10),
('Tagliatelle al Tartufo', 'Etxeko pasta trufa beltzarekin eta parmesano krema batekin.', '/static/img/tagliatelle.png', 16.00, 12),
('Ravioli di Ricotta e Spinaci', 'Ricotta eta espinaka betetako ravioli etxekoak, gurinarekin eta salbiarekin zerbitzatzen dira.', '/static/img/ravioli.png', 14.50, 12),
('Pappardelle al Cinghiale', 'Kebraburua eta belar aromatikoekin pappardelle.', '/static/img/pappardelle.png', 17.00, 8),
('Spaghetti alle Vongole', 'Txangurro freskuekin, baratxuri eta perrexilarekin egindako espaguetiak.', '/static/img/spaghetti_vongole.png', 15.00, 10),
('Lasagna Tradizionale', 'Haragiz eta besamel saltsaz egindako lasagna.', '/static/img/lasagna.png', 13.50, 10),
('Osso Buco alla Milanese', 'Pintxo txerri lentejan cook egina, gremolata eta risotto-rekin zerbitzatzen da.', '/static/img/osso_buco.png', 22.00, 8),
('Saltimbocca alla Romana', 'Serrano urdaiazpikoa eta salbia buztan itxuratu egindako oilasko bularra, ardo zuriarekin.', '/static/img/saltimbocca.png', 18.00, 10),
('Branzino al Sale', 'Gatzarekin egindako lubina, barazki erreakrekin.', '/static/img/branzino.png', 25.00, 5),
('Filetto di Manzo al Barolo', 'Barolo ardoan egindako behi filet, trufa puréarekin.', '/static/img/filetto.png', 28.00, 6),
('Pollo al Limone', 'Limoi eta belarretan marinatutako oilasko bularra, perfectuki egina.', '/static/img/pollo.png', 17.00, 10),
('Patate al Rosmarino', 'Erramu eta baratxuri-rekin egindako patatak.', '/static/img/patate_rosmarino.png', 5.50, 20),
('Verdure Grigliate', 'Denboraldiko barazkiak parrillan eginda, oliba olioarekin.', '/static/img/verdure.png', 6.00, 15),
('Risotto ai Funghi', 'Perretxiko krematsua risottoa.', '/static/img/risotto.png', 14.00, 10),
('Fagiolini al Vapore', 'Baldintza egonkorretan gatz-bilduko babak.', '/static/img/fagiolini.png', 6.50, 20),
('Polenta alla Griglia', 'Polenta parrillan eginda, tomate saltsarekin.', '/static/img/polenta.png', 8.00, 15),
('Tiramisu Classico', 'Kafe, mascarpone eta kakaoa dituena klasiko italiarra.', '/static/img/tiramisu.png', 7.50, 12),
('Panna Cotta al Caramello', 'Karamelo saltsarekin zerbitzatzen den panna cotta krematsua.', '/static/img/panna_cotta.png', 8.00, 10),
('Profiteroles al Cioccolato', 'Esne kremaz betetako profiterolak, txokolate beroarekin.', '/static/img/profiteroles.png', 9.50, 12),
('Crostata di Frutta', 'Musika garaian gainditzen diren fruta tarta bat.', '/static/img/crostata.png', 6.50, 10),
('Gelato Artigianale', 'Gelato artisauak hainbat zaporeetan (vanilla, txokolatea, pistatua).', '/static/img/gelato.png', 4.50, 20),
('Caffè Espresso', 'Italiar espresso kafea.', '/static/img/espresso.png', 2.50, 30),
('Caffè Corretto', 'Espresso bat likorekin.', '/static/img/caffe_corretto.png', 3.00, 20),
('Amaro', 'Hotz zerbitzatzen diren italiar digestiboak.', '/static/img/amaro.png', 4.00, 25),
('Grappa', 'Txikizketa italianoak, kopetan txikiak.', '/static/img/grappa.png', 5.00, 25),
('Limoncello', 'Hotz zerbitzatzen den limoizko likorea.', '/static/img/limoncello.png', 4.50, 20);
